### ISSUE TITLE
0.4.1 breaks openstack/barbican

### ISSUE THREAD

**Issue by tbreeds** [OpenKMIP/PyKMIP#113]
Openstack  consumes PyKMIP and in it's older kilo branch 

 Good: http://logs.openstack.org/44/246644/1/check/gate-barbican-python27/8824961/console.html.gz#_2015-11-17_23_20_38_489
 Bad: http://logs.openstack.org/44/246644/1/check/gate-barbican-python27/f560247/console.html#_2015-12-22_00_58_13_829

There are many difference between the good and bad runs BUT if I re-test locally with PyKMIP 0.4.0 the tests pass.  I believe that the following:
https://github.com/OpenKMIP/PyKMIP/commit/20dbad505520d654cbc9a4e6c6919233ef1bfc15

Is a backwards incompatible change and should have bumped the major version,

**Comment by joel-coffman** [comment]
Yes, the Barbican tests were reaching into some of the PyKMIP internals -- see [bug 1522856](https://bugs.launchpad.net/barbican/+bug/1522856). There is a change request to remove those assertions in the `stable/kilo` branch: https://review.openstack.org/#/c/257523/. I'll see if I can push that change along...

> I believe that the following `20dbad5` is a backwards incompatible change and should have bumped the major version

Yeah, we weren't expecting the Barbican unit tests to rely on PyKMIP's internal data structures, which are occasionally updated as new features are added.

**Comment by tbreeds** [comment]
Thanks. I'm getting a different back trace and that patch you refer to doesn't fix it for me (with 0.4.1)  I get:

 Traceback (most recent call last):
   File "barbican/tests/plugin/test_kmip.py", line 423, in test_store_private_key_secret_return_value
     return_value = self.secret_store.store_secret(secret_dto)
   File "barbican/plugin/kmip_secret_store.py", line 350, in store_secret
     self._raise_secret_general_exception(result)
   File "barbican/plugin/kmip_secret_store.py", line 589, in _raise_secret_general_exception
     raise ss.SecretGeneralException(msg) 
 barbican.plugin.interface.secret_store.SecretGeneralException: Problem seen during crypto processing - Reason: Status: ResultStatus.SUCCESS, Reason: None, Message: None
 ======================================================================
 FAIL: barbican.tests.plugin.test_kmip.WhenTestingKMIPSecretStore.test_store_symmetric_secret_return_value

Which seems to be because [result.result_status.enum](http://git.openstack.org/cgit/openstack/barbican/tree/barbican/plugin/kmip_secret_store.py?h=stable/kilo#n345)  is `<enum 'ResultStatus'>` and not ResultStatus.SUCCESS as expected.

Anyway this is largely moot.  Changing internal APIs is fine, the best fix IMO for Barbican in kilo is to limit pykmip which is being discussed here: https://review.openstack.org/#/c/260599/

We just need to work out the correct cap.
My suggestion is capping in <0.4.0 that way we're open to any critical security fixes in 0.3.X and we neatly do not overlap with the liberty requirements.

**Comment by joel-coffman** [comment]
Looks like https://review.openstack.org/#/c/260599/ is the correct path so I'm closing this issue.
