### ISSUE TITLE
default CLI args not over-written by config settings

### ISSUE THREAD

**Issue by bonzotronix** [OpenKMIP/PyKMIP#168]
I have a config file that contains

``` [server]
port=7000
```

However, the server still uses the default port value (5696).  I see that is because
1. the OptionParser has the "port" option using a default of 5696. This causes KmipServer._setup_configuration() to have its 'port' parameter set to 5696
2. KmipServer._setup_configuration() calls self.config.load_settings() _before_ handling the settings passed in its input arguments.

Fixing this may be as simple as moving the call to config.load_settings() down a few lines (after the handling of the input parameters).

**Comment by PeterHamilton** [comment]
Thanks for reporting this, I'm looking into it now.

**Comment by PeterHamilton** [comment]
I believe this was fixed with #217. If it recurs, definitely let me know.

**Comment by bonzotronix** [comment]
Thanks much!
