### ISSUE TITLE
How do I configure the username and password credentials on the server?

### ISSUE THREAD

**Issue by myrasaurus** [OpenKMIP/PyKMIP#182]
It seems that I have to specify the username and password (I provide bogus/bogus) to the client config, but I don't see any provision to do so for the server. And although the auth credentials are not configured on the server, the client requests somehow succeed. That looks like a bug.

Also, it seems that the code in from kmip.services.server.server is unable to parse username and password info. Is there a way to configure these when running the KMIP server?

**Comment by PeterHamilton** [comment]
You are correct, the software server does not configure accepted username/password credentials and does not verify those that are sent to it. Right now, the software server only authenticates based off of the client certificate used to establish the TLS connection to the server. The username/password configuration in the client (if not None/None) is sent with each request to the server but is ignored.

This obviously isn’t ideal and I am aware of that. Adding in request-level credential verification and enforcement is on my todo list.

**Comment by adityacb** [comment]
Thanks for the update. Yeah, I saw a bunch of TODOs for the credential stuff in the code. Should have taken a closer look earlier. I might take a stab at it if I get some time later this month.

Thanks,
Aditya

**Comment by PeterHamilton** [comment]
No problem. If you're interested in working on it, that would be great. It'll probably be a few weeks before I can get back to working on features for the library.

**Comment by PeterHamilton** [comment]
Hi @myrasaurus, it's been a while since we talked so I'm going to close this issue. I will be actively reworking user authentication on the software server in the next couple of months, so hopefully those improvements will address your original concerns. Feel free to comment further or file a new issue. Thanks!

**Comment by mshamn6x** [comment]
@PeterHamilton How do I configure PyKMIP server for username and password authentication.  It accepts whatever username and password. Kindly leave a reply.

I tried, adding authentication tag in request header as per KMIP spec, and provided linux login credential, key created, randomly I gave some other password it creates key anyway. Tried to add username and password field in server.conf. But there is no such configurations are available as of now. Then how to configure this credential authentication.

**Comment by PeterHamilton** [comment]
Hi @mshamn6x, thanks for reaching out. Username/password authentication is still unsupported for the PyKMIP server. It only uses the client certificate for client authentication. For more information, see the [server documentation](https://pykmip.readthedocs.io/en/latest/server.html#authentication).

**Comment by mshamn6x** [comment]
@PeterHamilton thanks man!
