### ISSUE TITLE
error in integration test using tox 

### ISSUE THREAD

**Issue by deepak-kumar1985** [OpenKMIP/PyKMIP#183]
We are getting issue using open ssl . We are trying to test open source KMIP server PYKMIP. For the same we have used tox utility which runs unit and integration test cases. First We got below error message while testing the same.

“SSLError: [Errno 1] _ssl.c:510: error:140890C7:SSL routines:SSL3_GET_CLIENT_CERT
IFICATE:peer did not return a certificate”

After searching through contents on internet ,We tried to use latest security certificates as recommended by below link:
ask/python-github2#58

But after doing recommended changes we are facing below issue:

“ERROR - [Errno 0] _ssl.c:344: error:00000000:lib(0):func(0):reason(0)”

Steps taken till now:
1) Updated security certificate with latest certificate file.
2) Installed httplib2.
3) Updated tox utility.
4) Generated self-signed security certificate.

But same problem persists. Please help on this issue.

**Comment by PeterHamilton** [comment]
Hi @deepak-kumar1985, thanks for filing this issue. I'm going to need additional information to help you here.

First, how are you invoking the tox integration tests and what does your configuration setup look like? Do you have certificates set up for both the client and server and are they signed correctly? Was the SSL error generated by the tox tests using the client or when running the server?

Unfortunately the GitHub issue you link to doesn't really apply in this case; it doesn't even reference the same SSL error you posted. As a result, the steps you took as a result of that issue may have introduced additional errors. I would undo those steps if possible so that you can repeat your initial test run and get the original SSL error.

**Comment by deepak-kumar1985** [comment]
thanks for quick response.Just to let you know about whole scenario.
I am invoking test suit using below command.
$ tox -e integration
as per documentation below comand was suggested.
tox -e integration -- --config <section-name> 
but I was not sure about section-name here . So I preferred it to default .Please note that unit test cases using tox uitlity have passed.
I have taken latest server certificate from below link.
https://code.google.com/archive/p/httplib2/issues/156
Before that I was using server.crt attached in pykmip itself. Which was giving me error of certificate expired.
I also used server certificate generated from below command.
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
my /etc/pykmip/server.conf is as given below:
  [client]
                               hostname=127.0.0.1
                               port= 5696
                               certificate_path=/root/PyKMIP/client.crt
                               key_path=/root/PyKMIP/client.key
                               ca_path=/root/PyKMIP/client.crt
                               username=None
                               password=None
                               timeout=30

      [server]
                               hostname=127.0.0.1
                               port=5696
                               certificate_path=/root/PyKMIP/server.crt
                               key_path=/root/PyKMIP/server.key
                               ca_path=/root/PyKMIP/server.crt
                               auth_suite=Basic
Please not that client has also been generated same way as server certificate. If above process is wrong let me know proper steps to generate security certificates for client and server side.
Here SSL error is generated when I start with tox utility as given above for integration test cases.

**Comment by PeterHamilton** [comment]
Ok, I think I know where your problems are coming from. First, when you invoke the tox integration tests, you do need to specify the configuration section that should be used for the client. In your example above, that would be the `[client]` section. That section tells the test suite what inputs to use when creating the client, which then allows the client to connect to the server you're testing against. For the tox integration tests, the configuration section *must* be defined in a `pykmip.conf` configuration file (see the README for more info). Here you have it in your `server.conf` file, which means it won't be read properly by tox.

Second, you need to read up on server and client certificates, how they work, and how to generate them. I recommend checking out the OpenSSL documentation and tutorials, they should point you in the right direction. Throw out the `httplib2` certificate you're using; it will not help you here. Once you've read up on OpenSSL and certificates, you should be able to use OpenSSL to generate your own server certificate and with it create and sign your own client certificate. Once you have both of those certificates, use them and their keys in your client and server configs above and you should be good to go.

When you have this configured properly, you should be able to run the following command and run the integration tests:
```
tox -e integration -- --config client
```

**Comment by PeterHamilton** [comment]
There could be a couple of issues at work here. The most common error I've seen when loading certificates occurs when the certificate files have the wrong file permissions. However, I think you may not be generating your certificates correctly.

When I generate certificates, I use the following OpenSSL commands:
* `openssl genrsa ...` to generate keys (if needed)
* `openssl req ...` to create self-signed CA certificates
* `openssl ca ...` to create certificates signed by the CA certificate
* `openssl x509 ...` to display certificates
Note here that generating your certificates with the right data and extensions will likely require you to set up your own custom OpenSSL configuration file. See the OpenSSL docs for more information on that.

Going back to the steps you listed above, you can ignore steps 1.3 and 1.4. You don't need your key in PKCS #12 format and the server does not care if your certificate is using a DER or PEM encoding.

For your client/server config settings, things are a bit jumbled. You currently only have two certificates, a CA certificate and a client certificate. You need a third certificate between these two, a server certificate that was signed by the CA and then was itself used to sign the client certificate. The server would use the server certificate and key for its `certificate_path` and `key_path` options and the CA certificate for its `ca_path` option. The client would use the client certificate and key for its `certificate_path` and `key_path` options while also using the CA certificate for its `ca_path` option. Without this setup, it's going to be challenging to establish any sort of successful secured connection.

Finally, the GitHub link you posted may or may not provide sufficient instructions for creating your certificates for your use case. The *best* resources here are the OpenSSL docs and tutorials so if you continue to have issues with your certificates, study them.
