### ISSUE TITLE
pykmip server resetting connection request from kmip4j client

### ISSUE THREAD

**Issue by deepak-kumar1985** [OpenKMIP/PyKMIP#184]
I am trying to connected to pykmip server from kmip4j client but I am getting below message in server logs.

 "kmip.server - ERROR - [Errno 1] _ssl.c:510: error:1408
 F10B:SSL routines:SSL3_GET_RECORD:wrong version number"

I have created server certificates using below openssl commands.

openssl genrsa -des3 -out server.orig.key 2048
openssl rsa -in server.orig.key -out server.key
openssl req -new -key server.key -out server.csr
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

On client side I am using kmip4j taken from github link.I use below command to bring up gui interface of client working on ubuntu.

java -cp "./gui/target/classes:./core/target/classes:/usr/share/maven-repo/org/slf4j/slf4j-api/1.6.4/:/usr/share/maven-repo/org/slf4j/slf4j-api/debian:/usr/share/maven-repo/org/slf4j/slf4j-api-1.7.21.jar:/usr/share/maven-repo/org/slf4j/slf4j-simple-1.7.2.jar:/usr/share/maven-repo/org/slf4j/impl/slf4j-simple-1.7.21.jar:./utils/target/kmip4j-utils-1.0.jar:./core/target/kmip4j-core-1.0.jar:./kmls/kmls/target/kmip4j-kmls-1.0.jar:./kmls/kmls-db/target/kmip4j-kmls-db-1.0.jar" ch.ntb.inf.kmip.client.gui.KMIPClientGUI

Solutions: Solution provided on different forums suggest disabling specific sslv version.
But I am getting a way of disabling this version with kmip4j client.
Please help

**Comment by PeterHamilton** [comment]
I'm not familiar with using the kmip4j client. However the error you're seeing indicates that the likely problem is an SSL/TLS mismatch. The PyKMIP server will only establish TLS 1.0/1.2 connections, depending upon the version of Python being used. If the kmip4j client can only establish SSL connections it will not be able to connect to the server.

Right now there is no way to disable TLS for the PyKMIP server. If the kmip4j client cannot use, or be upgraded to use, a more secure version of TLS it will not be able to connect to the server. However, this would also be true if you were using this client to connect to a certified KMIP appliance. To be KMIP compliant, an appliance *must* only support TLS 1.0/1.2. Anything else is insufficient.
