### ISSUE TITLE
Fails pep8 test

### ISSUE THREAD

**Issue by toothwalker** [OpenKMIP/PyKMIP#199]
kmip/services/kmip_client.py:228:15: F821 undefined name 'e'

```
        for host in self.host_list:
            self.host = host
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self._create_socket(sock)
            self.protocol = KMIPProtocol(self.socket)
            try:
                self.socket.connect((self.host, self.port))
            except Exception as e:
                self.logger.error("An error occurred while connecting to "
                                  "appliance " + self.host)
                self.socket.close()
            else:
                return

        self.socket = None
        raise e
```
Obviously on the last line "raise e", e is not in scope. I assume the last two lines should be moved into the expect block.

**Comment by PeterHamilton** [comment]
@toothwalker Thanks for filing this. For-loops don't actually define their own scope so the reference to `e` in the `raise` call is legitimate. Are you actually seeing a `pep8` error from this when you run `tox -e pep8`?

Regardless of scoping, I don't like having the `raise` call outside the `except` block like this, so I'll fix it.

**Comment by toothwalker** [comment]
Yes I was running "tox -e pep8" and got the following error:
kmip/services/kmip_client.py:228:15: F821 undefined name 'e'

I believe the problem isn't the "for" loop. It is that "e" isn't assigned until it enters the exception handler (except Exception as e).

**Comment by PeterHamilton** [comment]
Huh, that's bizarre. I've been running `pep8` on this code for a year and haven't seen that error. Out of curiosity, what version of Python are you running?

**Comment by toothwalker** [comment]
Python 2.7.12 is the default. Python 3.5.2 is also on the machine. I haven't looked the scripts to see if it is explicitly calling for Python 3.FYI I'm running Linux Mint 18

**Comment by toothwalker** [comment]
Correct me if I'm wrong. But it looks like you are using flake8 for pep8 tests. My flake8 is indeed using Python 3.

flake8 --version
2.5.4 (pep8: 1.7.0, pyflakes: 1.1.0, mccabe: 0.2.1) CPython 3.5.2 on Linux

**Comment by PeterHamilton** [comment]
You're correct, we are using `flake8`. When I look at the libraries installed for these runs (whether on my local system or in Travis), I see the following:

`flake8`: 3.0.4
`mccabe`: 0.5.2
`pyflakes`: 1.2.3

And this all runs on Python 2.7.9 (at least for Travis). It's possible that you're seeing this error due to using older versions of these libraries.

**Comment by PeterHamilton** [comment]
In the process of looking through this code again I remembered why the `raise` statement is outside the loop. We only want to raise an exception if none of the potential endpoints can be connected to. If some fail, we just log the failure and keep trying. #201 simply removes the use of `e` outside the except block, which should resolve your `pep8` error, while still retaining original functionality.

**Comment by toothwalker** [comment]
I upgrade flake8, pyflakes, and mccabe to the same versions as you. I still had the error...But your patch fixed it. Thank you.

**Comment by PeterHamilton** [comment]
Glad to hear it. If you see any other errors like that pop up, definitely file more issues.
