### ISSUE TITLE
Add optional 'name' argument to Create and Create Key Pair functions

### ISSUE THREAD

**Issue by jseadragon** [OpenKMIP/PyKMIP#208]
It would be helpful if we could add an optional 'name' keyword to some of the operations in  `ProxyKmipClient` and possibly `KMIPProxy`. Notably, these operations:
 * `Create`
 * `Create Key Pair`

I don't think this would be a large change (I've got it working already for `Create`) and wouldn't break backwards compatibility (as it would default to not specifying the name).

If I went ahead and added this, would it be something you would consider accepting in a pull request?

**Comment by PeterHamilton** [comment]
Yes, I would accept that addition specifically for the `ProxyKmipClient` methods. As you said, these should be optional parameters that default to `None`.

For the `KMIPProxy`, name attributes should be included in the template attribute argument for those methods.

**Comment by jseadragon** [comment]
For the `create_key_pair` function, it seems to make sense to add a `private_name` and a `public_name` keyword, instead of just a single `name` field that we would either duplicate or add a suffix to. These would be optional parameters that default to `None`, just like with the `create` method.

Alternatively, maybe it could accept a `list`.

This provides the most flexible usage to people using the library. What do you think?

**Comment by PeterHamilton** [comment]
Yep, `public_name` and `private_name` parameters sound good to me. The KMIP specification explicitly states that the names for public/private key pairs will not necessarily be the same, so this makes sense.

**Comment by jseadragon** [comment]
At [core/factories/attribute_values.py:113](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/core/factories/attribute_values.py#L113), we are returning a `Name` object. Is this supposed to return a `NameValue` instead?

**Comment by PeterHamilton** [comment]
Nope, the `Name` object is the attribute value. It's can be a little confusing. In this case, the `NameValue` contains the actual name string (e.g., "Peter"). However, the `Name` object contains both the value and the type of the name string; according to the KMIP specification, these name types include `Uninterpreted Text String` and `URI`. The value of a `Name` attribute object contains two things, the name itself ("Peter") and the name type ("Uninterpreted Text String").

In terms of the overall `Attribute` structure, it would look like this:

    Attribute:
        Attribute Name: Name
        Attribute Index (optional): 1
        Attribute Value:
            Name Value: Peter
            Name Type: Uninterpreted Text String

**Comment by jseadragon** [comment]
Ah ok, awesome. Thanks for the explanation - it seemed confusing since there was an `attribute` factory, as well as an `attribute_value` factory.

I have a working patch, just need to do some cleanup and I'll throw it your way.

**Comment by PeterHamilton** [comment]
Awesome, thanks!

Yeah, the factory code is old and kludgy. Those two factories should really just be merged together, I just haven't gotten around to fixing them.

**Comment by jseadragon** [comment]
Do you want me to add `closes #208` in the commit message? I submitted the PR here. Never actually submitted a GitHub PR before, so this is an new process for me 

https://github.com/OpenKMIP/PyKMIP/pull/224

**Comment by PeterHamilton** [comment]
Only if you want to. It's nice 'cause you don't have to manually clean up issue threads. If you don't I'll just close it manually.

**Comment by jseadragon** [comment]
Updated with a new commit message
