### ISSUE TITLE
policy_path error when running server

### ISSUE THREAD

**Issue by dheding** [OpenKMIP/PyKMIP#210]
I'm receiving the following error when attempting to run the PyKMIP server 0.5.0:
"kmip.core.exceptions.ConfigurationError: Setting 'policy_path' is missing from the configuration file."

I cannot find policy_path documented anywhere and have not found any guidance online.  I have attempted to insert a path statement in the config file the error then changes to:
"kmip.core.exceptions.ConfigurationError: The policy path value, if specified, must be a valid string path to a filesystem directory."   The path I used is a valid path with appropriate permissions but not knowing the format of the expected policy file I am unable to provide a suitable target. 

Any guidance would be appreciated.

**Comment by PeterHamilton** [comment]
Yep, this is a new feature that was added recently. I'll be publishing an update to the README as well as some additional documentation to the GitHub wiki within the next week or so.

For now, you can add the following line to your config file and the error should go away:

`policy_path=`

**Comment by dheding** [comment]
Peter thank you for your quick response.   I attempted the "policy_path=" resolution but am still seeing the same error.  I use the default path location for the server.conf file and have double checked to make sure that there is no ./pykmip/server.conf file on the home directory of the user being used to run the server.  Below is the command used to run the server(run from the PyKMIP root):
python bin/run_server.py

The /etc/pykimp/server.conf file is listed below:
[server]
#host=127.0.0.1
hostname=127.0.0.1
port=5696
#keyfile=/opt/app/kmip/PyKMIP-master/kmip/demos/certs/server.key
key_path=/opt/app/kmip/PyKMIP_0.5.0/PyKMIP-master/kmip/demos/certs/server.key
#certfile=/opt/app/kmip/PyKMIP-master/kmip/demos/certs/server.crt
certificate_path=/opt/app/kmip/PyKMIP_0.5.0/PyKMIP-master/kmip/demos/certs/server.crt
#cert_reqs=CERT_NONE
#ssl_version=PROTOCOL_SSLv23
#ca_certs=None
ca_path=/opt/app/kmip/PyKMIP_0.5.0/PyKMIP-master/kmip/demos/certs/server.crt
auth_suite=Basic
#policy_path=/etc/pykmip/policies
#policy_path=None
policy_path=
#do_handshake_on_connect=True
#suppress_ragged_eofs=True

**Comment by PeterHamilton** [comment]
Hmmm, ok, I'll look into this more tomorrow.

**Comment by dheding** [comment]
Thanks Peter.  I really appreciate your help.

**Comment by PeterHamilton** [comment]
Ok, this is a bug. You should be able to leave the `policy_path` unset if you're not using your own object policies, but right now you have to set it to a valid system directory. I'll post a fix.

**Comment by dheding** [comment]
Thank you Peter.  I did put in a default policy path with the target file the result of a touch command and it now appears that the server is starting.   Thank you for your assistance.

**Comment by PeterHamilton** [comment]
Yep, that would fix it. I'm updating the server to silently handle an unset or missing `policy_path` config option, that way upgrading the library won't just break things. I should have that out in an hour or two.

**Comment by PeterHamilton** [comment]
#215 should fix this going forward. Let me know if you still see errors relating to `policy_path`.
