### ISSUE TITLE
General question on testing client functions

### ISSUE THREAD

**Issue by dheding** [OpenKMIP/PyKMIP#244]
Can anyone point me to examples using the PyKMIP client for CreateKeyPair  in either the original client or the pie client.   I've looked in kmip/demos and see the various py files but I was hoping to find a listing of example runs with sample arguments provided.   Thanks in advance for any guidance.

**Comment by PeterHamilton** [comment]
Good question. We don't currently have docs with those types of examples. The following is a common set of arguments for creating a key pair:

`python create_key_pair.py -a RSA -l 2048`

The algorithm and key lengths will vary depending upon what is supported by your KMIP appliance, so check its documentation.

I'll add a TODO to get started on some docs for PyKMIP that will highlight which algorithms are supported in the KMIP spec.

**Comment by dheding** [comment]
Thank you.

**Comment by PeterHamilton** [comment]
I've added some info to the wiki listing what algorithms are supported by the KMIP spec; see the [FAQ](https://github.com/OpenKMIP/PyKMIP/wiki/Frequently-Asked-Questions).

**Comment by PeterHamilton** [comment]
I'm going to go ahead and close this. If you have further questions, just let me know.
