### ISSUE TITLE
a bug in kmip/demos/units/create_key_pair.py

### ISSUE THREAD

**Issue by vbnmmnbv1986** [OpenKMIP/PyKMIP#249]
> 

    name = Attribute(attribute_name=name, attribute_value=value)
    name = Attribute.AttributeName('Cryptographic Usage Mask')
    value = CryptographicUsageMask(
        UsageMaskEnum.ENCRYPT.value | UsageMaskEnum.DECRYPT.value)
    usage_mask = Attribute(attribute_name=name, attribute_value=value)
    attribute_type = AttributeType.CRYPTOGRAPHIC_LENGTH
    length_obj = attribute_factory.create_attribute(attribute_type,
                                                    length)
    attributes = [algorithm_obj, length_obj, name, usage_mask]

> 

This will not work. Two 'name' assignment? I think it should be something like:

> 

    name = Attribute(attribute_name=name, attribute_value=value)
    name_mask = Attribute.AttributeName('Cryptographic Usage Mask')
    value = CryptographicUsageMask(
        UsageMaskEnum.ENCRYPT.value | UsageMaskEnum.DECRYPT.value)
    usage_mask = Attribute(attribute_name=name_mask, attribute_value=value)

    attribute_type = AttributeType.CRYPTOGRAPHIC_LENGTH
    length_obj = attribute_factory.create_attribute(attribute_type,
                                                    length)
    attributes = [algorithm_obj, length_obj, name, usage_mask]

>

**Comment by PeterHamilton** [comment]
Thanks for posting this. You are correct, the `Name` attribute gets dropped here and is never sent with the create request. I've confirmed the bug on my end and the fix as well, which should hopefully get merged soon.

I remember running across this bug a while back and it completely slipped my memory, so thank you again for the reminder.
