### ISSUE TITLE
about locate operaton

### ISSUE THREAD

**Issue by vbnmmnbv** [OpenKMIP/PyKMIP#258]
Hi Peter,

Can I ask you two questions?

1. Do you have any ETA for the next release?

2. Currently I need an operation to "list" all the existing keys on the server. Should be "locate". Seems that currently it's not supported by server. 
I checked the SPEC, maximum items/storage status mask/object group member are all non-trivial features to support, I think. 
So do you think currently it makes sense to implement a simple locate operation which will just return uuids of all the existing managed objects of the server without any filtering? Later we can add the filtering piece by piece.

**Comment by PeterHamilton** [comment]
1. I usually cut a new release every 4-5 months or so, depending on how much work has been done with the library in that time. 0.7.0 will probably come out sometime in April.

2. Yes, a full-featured version of `locate` is challenging to support. I'm fine with a simple, bare bones version that only lists the UUIDs of the objects belonging to a specific user. That's a reasonable first cut on it.
