### ISSUE TITLE
client.py argument checking

### ISSUE THREAD

**Issue by vbnmmnbv** [OpenKMIP/PyKMIP#261]
Hi Peter,

When I am working on adding the pie support for locate operation, I do notice that there are some issues about the arguments checking in client.py. It's too strict, I think. For example, for get() operation,  from the spec, uid can be ignored  while it must be a string in the codes. This means that using the pie interface, I can not issue an get request without any uid? 

Should we refactor this some time? I think your vision is to put all the argument validation inside the payload module in the future?

**Comment by PeterHamilton** [comment]
Good point, `Get` and `Destroy` should allow `None`. The underlying `KMIPProxy` client already works this way. I've pushed a patch updating these.

**Comment by PeterHamilton** [comment]
I need to rebase #262 before this is closed. I'll do that tomorrow.
