### ISSUE TITLE
ETA for my commits?

### ISSUE THREAD

**Issue by vbnmmnbv** [OpenKMIP/PyKMIP#281]
Hi Peter,
I have seen the commits are pending there for a long time.
Probably you are busy:) But can I ask an ETA for merging? No hurry~
Let me know if there is any issue. Thanks.

**Comment by PeterHamilton** [comment]
Yeah, I've been swamped lately. I'll make an effort to get reviews out on those later today.

Also, feel free to just send me an email for this type of question. No need to file an issue.

**Comment by vbnmmnbv** [comment]
Thanks. BTW, where can I find your email address?

**Comment by PeterHamilton** [comment]
Whoops, sorry 'bout that. It was hidden on my profile. It's public now.
