### ISSUE TITLE
add key wrapping support encrypt decrypt signature and signature verify

### ISSUE THREAD

**Issue by br9191fr** [OpenKMIP/PyKMIP#285]
Hello everybody
For one project I have to implement KMIP functionalities (client side) missing from this project
key wrapping support
encrypt and decrypt (executed on server)
signature and signature verify (executed  on server)
Those functionalities exist in the KMIP server I have to connect
Before beginning the development, 
1/ I would like to know if somebody has already done one of these
2/ I saw that in pull request key wrapping support was proposed long time ago but developments were never integrated in the project? Can you explain me why ? Those developments are out of sync from the master branch but part of the code can be reused, so should I start with it or restart from start ?

Thanks in advance

Bruno

**Comment by PeterHamilton** [comment]
Hi @br9191fr. Hold off on getting started on that feature set actually. All of those features are actively being worked on from my end and should get merged into master within the next month.

As for the original key wrapping patch from way back, it's getting pulled forward with some tweaks to make it compatible with the current state of the code base. I believe the issue that blocked merging it had to do with testing the feature but that should be handled this go round.
