### ISSUE TITLE
cryptography>=1.1 ?

### ISSUE THREAD

**Issue by vbnmmnbv** [OpenKMIP/PyKMIP#301]
I have  found in your requirements.txt you specify cryptography>=1.1.
However, I found at least in version 1.2.3, 'ANSIX923' doesn't exist. So should we update the info?

`
>>> import cryptography as c
>>> c.__version__
'1.2.3'
>>> from cryptography.hazmat.primitives import padding as symmetric_padding
>>> dir(symmetric_padding)
['AlreadyFinalized', 'PKCS7', 'PaddingContext', '_PKCS7PaddingContext', '_PKCS7UnpaddingContext', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'abc', 'absolute_import', 'division', 'lib', 'print_function', 'six', 'utils']`

`
>>> import cryptography as c
>>> c.__version__
'1.7.2'
>>> from cryptography.hazmat.primitives import padding as symmetric_padding
>>> dir(symmetric_padding)
['ANSIX923', 'AlreadyFinalized', 'PKCS7', 'PaddingContext', '_ANSIX923PaddingContext', '_ANSIX923UnpaddingContext', '_PKCS7PaddingContext', '_PKCS7UnpaddingContext', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_byte_padding_check', '_byte_padding_pad', '_byte_padding_update', '_byte_unpadding_check', '_byte_unpadding_update', 'abc', 'absolute_import', 'division', 'lib', 'print_function', 'six', 'utils']`

**Comment by PeterHamilton** [comment]
Good catch. It looks like 1.3 is the first minor release that supports ANSIX923 padding. I'll do some tests to make sure 1.3 is compatible and then update requirements.
