### ISSUE TITLE
ssl.SSLError: [SSL] PEM lib (_ssl.c:2964)

### ISSUE THREAD

**Issue by prasad7nara** [OpenKMIP/PyKMIP#352]
KMIP client is failing to connect with ssl error, I have proper certificates and verified connection using openSSL s_client connect. Not able to figure out why connection is failing with KMIP client. It would be great if someone can help me on this.

`5268 21284 10/06 20:08:58 DEBUG KMIPProxy keyfile: C:\Encryption\SafeNetCerts\clientkey
5268 21284 10/06 20:08:58 DEBUG KMIPProxy certfile: C:\Encryption\SafeNetCerts\signed.crt
5268 21284 10/06 20:08:58 DEBUG KMIPProxy cert_reqs: 2 (CERT_REQUIRED: 2)
5268 21284 10/06 20:08:58 DEBUG KMIPProxy ssl_version: 2 (PROTOCOL_SSLv23: 2)
5268 21284 10/06 20:08:58 DEBUG KMIPProxy ca_certs: C:\Encryption\SafeNetCerts\MyCA.crt
5268 21284 10/06 20:08:58 DEBUG KMIPProxy do_handshake_on_connect: True
5268 21284 10/06 20:08:58 DEBUG KMIPProxy suppress_ragged_eofs: True

ssl.SSLError: [SSL] PEM lib (_ssl.c:2964)`

**Comment by PeterHamilton** [comment]
Hi @prasad7nara, I'm happy to help. OpenSSL errors are always tricky to debug. I'm in the process of collecting common SSL errors that users encounter for an upcoming FAQ update, along with solutions to resolving those errors. I haven't seen a `[SSL] PEM lib` error before, so this will be a nice addition.

I would start by verifying that all of your key and certificate files are actually in PEM format. Open each file and verify that it has readable text headers and footers, something like these:

```
$ cat clientkey
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

```
$ cat signed.crt
Certificate:
...
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

The certificates may or may not have the parsed `Certificate:` section before the actual certificate bytes. 

Verify that OpenSSL can actually load and display the contents of the key and certificate files. For the key file use:

```
$ openssl rsa -noout -text -in clientkey
```

For the certificate files use:

```
$ openssl x509 -noout -text -in signed.crt
$ openssl x509 -noout -text -in MyCA.crt
```

Using the output for the two `openssl x509` commands above, double check that the validity dates are valid for the current time. The current date and time should be between the `Not Before` and `Not After` dates.

Using the output from the `openssl rsa` command the `openssl x509` command for `signed.crt`, triple check that the `modulus` and `publicExponent` fields of the key match the `Modulus` and `Exponent` fields of the certificate. If these do not match, the key is not valid for the certificate.

Finally, from your config log it looks like you are running the PyKMIP client on Windows. I have never tested PyKMIP on Windows, so it is quite possible that there are PyKMIP bugs for that platform I haven't discovered yet. If you continue to have problems on Windows, I would recommend trying to use the PyKMIP client with your key and certificate files on a Linux machine, just to determine if the error you see still occurs.

Let me know if any of these debugging steps highlights a problem or resolves your issue. If none of these help, we'll have to dig a little deeper.

**Comment by prasad7nara** [comment]
Hi Peter,
Thanks for looking into this.
I have identified the issue, we get this error when wrong private key pass phrase is provided in the config.  I didn't even think about this before since it used to work for me but due to some recent changes in my application wrong pass phrase is getting passed to cmd (we store encrypted pass phrase in our application DB the decryption value coming up as wrong due to some recent changes in my application which I'm not aware of).

Apologies for false alarm.

**Comment by PeterHamilton** [comment]
Not a problem @prasad7nara, I'm glad you were able to figure out the problem.
