### ISSUE TITLE
Newer Protocols

### ISSUE THREAD

**Issue by ddurham2** [OpenKMIP/PyKMIP#356]
The README.md states that v1.2 is currently supported.  Is there a roadmap for supporting newer versions and their features or is this just not on the horizon?

Are there plans for supporting more profiles than just the Basic Discover?

**Comment by PeterHamilton** [comment]
Hi @ddurham2, apologies for the delay on answering this. I missed the issue notification and have been busy on other projects.

The README is correct regarding 1.2 support, however we do have a few minor 1.3 / 1.4 features supported as well (e.g., attributes, object arguments). We don't have any major 1.3 / 1.4 features supported just yet (e.g., operations).

The long term plan for PyKMIP is to fully support every feature of the KMIP specification, from 1.0 to the latest version, now 1.4. The focus lately has been on adding in 1.2 cryptographic operations, like encrypting/decrypting/signing data and wrapping/deriving encryption keys. We'll be cutting the next release, 0.7, within the next few weeks and then after that I'll continue working on outstanding features and pull requests.

In general, I have a long list of features covering the different KMIP versions that I'm slowly working my way through. However, if you have a specific feature that you are interested in, definitely file an issue and I'll bump it up my priority queue.

Regarding client/server profiles, it's really just a matter of adding in the underlying features that make up a given profile. Once those features are supported, the profile is supported. My intent is to eventually support all profiles. Additionally, official support for the different KMIP profiles was better codified in 1.3 and 1.4 (i.e., official enumerations now exist for each recognized profile). Before the profiles and their names/definitions would kind of change from version to version. Now that a standardized list exists, it should be easier to break down support and map out development for each one.

**Comment by ddurham2** [comment]
Peter, thank you for the information.  That's helpful.  Feel free to close the issue.

**Comment by PeterHamilton** [comment]
No problem @ddurham2, thanks for reaching out.
