### ISSUE TITLE
client certificate verification failed when running client demo script

### ISSUE THREAD

**Issue by gaurav36** [OpenKMIP/PyKMIP#385]
Hello team,

I am using PyKMIP for one of my application. I generated self signed server certificate using below oracle doc:
https://docs.oracle.com/cd/E52668_01/E54669/html/ol7-self-cert.html

i then generated self signed client_private_key.pem and then generated client_cert.pem using CAcert.pem and CAcert-key.pem that i generated during server certificate.

Now i am running server. it runs successfully.

When i am trying to run client demo script demos/units/create_key_pair.py its giving certificate verification failed error. Am i missing anything ?

 ``01:45 PM Mon Jan 22# python demos/units/create_key_pair.py --algorithm AES -l 256 -n=gaurav
No handlers could be found for logger "kmip.services.kmip_client"
Traceback (most recent call last):
  File "demos/units/create_key_pair.py", line 90, in <module>
    client.open()
  File "/usr/lib/python2.7/site-packages/kmip/services/kmip_client.py", line 223, in open
    raise last_error
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)``

Thank you,

**Comment by PeterHamilton** [comment]
Hi @gaurav36, thanks for filing this issue. To debug this, first verify that your ``pykmip.conf`` file is configured correctly and is pointing to the right certificate and key files for the client and CA. See [here](https://pykmip.readthedocs.io/en/latest/client.html#configuration) for more information.

Second, verify that your ``server.conf`` file is configured correctly and is pointing to the right certificate and key files for the server and CA. See [here](https://pykmip.readthedocs.io/en/latest/server.html#configuration) for more information.

Third, verify that your client certificate was correctly signed by your CA certificate. You should be able to use the following command to do so:

```
$ openssl verify -CAfile <path/to/your/CA/certificate> <path/to/your/client/certificate>
```

If all three of these steps are verified, you should be able to connect the client and server. If you still have problems, post the errors you are seeing and we will continue from there.

**Comment by gaurav36** [comment]
Hello @PeterHamilton  
Thank you very much for your reply.

I was having issue in client and server certificate. Its verification was failing because i was using same name for my client and server and CA certificate.

Now i made these certificate verified successfully.

 05:03 PM Mon Jan 22# openssl verify  /etc/openldap/certs/CAcert.pem /etc/pykmip/cert2/client_cert.pem /etc/pykmip/cert3/server-cert.pem 
/etc/openldap/certs/CAcert.pem: OK
/etc/pykmip/cert2/client_cert.pem: OK
/etc/pykmip/cert3/server-cert.pem: OK

but now when running client i mean from demo to generate key pair i get following error:

root@master /home/ggarg/pykmip/kmip :)
 05:25 PM Mon Jan 22# python demos/units/create_key_pair.py --algorithm AES -l 256 -n=gaurav
Traceback (most recent call last):
  File "demos/units/create_key_pair.py", line 90, in <module>
    client.open()
  File "/usr/lib/python2.7/site-packages/kmip/services/kmip_client.py", line 209, in open
    self._create_socket(sock)
  File "/usr/lib/python2.7/site-packages/kmip/services/kmip_client.py", line 234, in _create_socket
    suppress_ragged_eofs=self.suppress_ragged_eofs)
  File "/usr/lib64/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 554, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory

**Comment by PeterHamilton** [comment]
Hi @gaurav36, were you able to resolve your configuration issue?

**Comment by gaurav36** [comment]
Hello @PeterHamilton  
Thank you very much for your quick help. There was problem in client config file pykmip.conf regarding the typo in private key. but now it sovled. I was having another problem regarding extension in certificate but it also solved by re generating CA with extension and key usage :)

Thank you again for your help :)

**Comment by PeterHamilton** [comment]
No problem, I'm glad you got everything working. I'll close this issue for now.

If you have any other questions, just let me know.

**Comment by gaurav36** [comment]
@PeterHamilton 
Hello Peter, 
I am having one more question regarding key extraction. i see in demos/utils.py that you can get key_material and when you print "format(repr(key_material))" you will get "KeyMaterial(value='.61\xf2lO\x0bO\xb2\x06WC\x199\x05\xc7')" 

is there any way to get only key i mean to get .61\xf2lO\x0bO\xb2\x06WC\x199\x05\xc7 value .

Thanks,

**Comment by PeterHamilton** [comment]
Sure. The `KeyMaterial` object is a structure containing the key bytes along with other key metadata. If you just want the bytes of the key value, do the following:

```
key = client.get(...)
key_bytes = key.key_block.key_value.key_material.value
```

However, the demo you're looking at uses the old `KMIPProxy` client. I'd recommend using the newer `ProxyKmipClient` client. Getting the key bytes is much easier:

```
from kmip import pie
client = pie.ProxyKmipClient(...)
...
key = client.get(...)
key_bytes = key.value
```

**Comment by gaurav36** [comment]
@PeterHamilton 
Thank you very much for your reply. i am able to get the key value with respect to last UUID.
