### ISSUE TITLE
Feature request: check, rekey operations

### ISSUE THREAD

**Issue by randombit** [OpenKMIP/PyKMIP#405]
Sorry I know I am being a pain.

Is there any chance for adding the `check` and `re-key` operations to PyKMIP? It seems that "Re-key key pair" is implemented but not the corresponding version for symmetric keys. And `check` is very useful in conjunction with sequenced operations in a batch.

Alternately if you are not interested in adding these, would you accept a PR?

**Comment by PeterHamilton** [comment]
@randombit Don't worry about it, I'm glad you're finding the library useful. Working with users/developers and improving the project is part of why I enjoy working with open source software.

I can definitely start work on ``check`` and ``rekey`` support, though it may take me a week or two to get those done. I don't know what your timeline looks like, so let me know if that won't work for you.

I'm also always willing to review and accept PRs, if you're willing to put in the dev time. Working with some lower level internal aspects of the library can be painful, so let me know if you want to go that route and I can provide pointers.

**Comment by PeterHamilton** [comment]
@randombit It looks like I already have partial support for the ``check`` operation implemented, so updating the client(s) to support it shouldn't take much time at all. ``rekey`` will require a little more time.

**Comment by randombit** [comment]
Having these in the next few weeks would be perfect for us, I have a lot of other work to do on our side (which PyKMIP is helping with) and can circle back to the dependencies on check and rekey later. Thank you very much for your help and this great software package.

**Comment by PeterHamilton** [comment]
@randombit I don't have an endpoint available to test ``Check`` and ``Rekey``, so let me know if you encounter any client errors with these once they're merged. ``Check`` should be good to go, I hope to have ``Rekey`` done in a few days.

**Comment by randombit** [comment]
@PeterHamilton Thanks so much! I should be able to check these sometime next week.
