### ISSUE TITLE
Operations taking CryptographicParameters fail if set to default None

### ISSUE THREAD

**Issue by randombit** [OpenKMIP/PyKMIP#406]
If you call `encrypt` (or I think anything else taking a `cryptographic_parameters` argument) without specifying the `cryptographic_parameters`, an exception is thrown:

```client.encrypt(b"some data", uuid)```

raises

```
  File "/usr/lib/python3.6/site-packages/PyKMIP-0.8.dev0-py3.6.egg/kmip/pie/client.py", line 1252, in _build_cryptographic_parameters
    raise TypeError("Cryptographic parameters must be a dictionary.")
```

The problem is `encrypt` checks for and accepts the default None, but it then passes its argument to `self._build_cryptographic_parameters` which accepts only a dict.

I think all that is required is to add something like

if value is None:
   value = {}

at the start of `_build_cryptographic_parameters`

**Comment by PeterHamilton** [comment]
@randombit Totally missed the notification on this, sorry for the delay.

I agree with your assessment, that looks like the problem. I'll try to get a fix posted later today.

**Comment by randombit** [comment]
Thanks!
