### ISSUE TITLE
Need  help to create Object group and regsiter a device

### ISSUE THREAD

**Issue by prputtur** [OpenKMIP/PyKMIP#452]
I have a requirement to create a Object group in PyMIP server and register a device (Flash storage device ) into it for  Symmetric key management.
Can you please provide information on this

**Comment by PeterHamilton** [comment]
Hi @prputtur, thanks for filing your first issue. I'm going to need more information from you to fully answer your question.

The first part of your issue, creating object groups, requires PyKMIP support for the `ObjectGroup` attribute. That work needs to be done.

The second part of your issue, registering a Flash storage device for symmetric key management, is unclear to me. Do you mean that you want to use a Flash storage device to store the symmetric keys created by the PyKMIP server? If so, you should be able to do this by setting the `database_path` configuration setting in the server config file. Set it to a system path that points towards wherever your Flash storage device is mounted and the server SQLite database file will be stored on the device.

If that's not what you mean, please provide additional information on what functionality you're specifically thinking of.

**Comment by prputtur** [comment]
Second part is  to use Flashstorage device as a client for for storing the user data in a safe manner, the keys will be stored in Server only.

Please do let me know any clue on ``` The first part of your issue, creating object groups, requires PyKMIP support for the ObjectGroup attribute. That work needs to be done.  ``` -is there a way to proceed

**Comment by PeterHamilton** [comment]
> Second part is to use Flashstorage device as a client for for storing the user data in a safe manner, the keys will be stored in Server only.

By user data, do you mean the client certificates/credentials for accessing the server? If so, that's fine, just be sure to point to the right certificate files on your Flash storage device when using the PyKMIP client (or update the client configuration file to point to the right files on your Flash device). If not, I don't know what you mean.

For more information on authentication with the PyKMIP client and server, see the [server docs](https://pykmip.readthedocs.io/en/latest/server.html#authentication). A test script for creating example certificates can be found [here](https://github.com/OpenKMIP/PyKMIP/blob/master/bin/create_certificates.py). Beyond that, there's no further registration needed.

As for `ObjectGroup` attribute support, development work needs to be done to add that capability to PyKMIP. Either I will need to do it at some point or someone else will. I'm too busy right now to work on it; I may have some free time open up in a few weeks, we'll see. You're free to take a crack at the development if you want. See the [dev docs](https://pykmip.readthedocs.io/en/latest/development.html) for more info.

**Comment by PeterHamilton** [comment]
Just a heads up that `ObjectGroup` attribute support is now officially supported by PyKMIP (see #593 and #594).

Given this issue is a year old, I'm going to go ahead and close it.
