### ISSUE TITLE
Started seeing `Error parsing Protocol Version Minor` when upgraded to v0.8.0

### ISSUE THREAD

**Issue by keyurgolanins** [OpenKMIP/PyKMIP#470]
Getting this issue with v0.8.0 while locating a resource from safenet server.

Isn't getting this error for the same configuration and same resource when I use v0.6.0.

`{'message_extension': None, 'result_status': Enumeration(enum=ResultStatus, value=ResultStatus.OPERATION_FAILED, tag=Tags.RESULT_STATUS), 'response_payload': None, 'result_message': ResultMessage(value='Error parsing Protocol Version Minor'), 'unique_batch_item_id': None, 'result_reason': Enumeration(enum=ResultReason, value=ResultReason.INVALID_MESSAGE, tag=Tags.RESULT_REASON), 'length': 96, 'tag': <Tags.RESPONSE_BATCH_ITEM: 4325391>, 'async_correlation_value': None, 'payload_factory': <kmip.core.factories.payloads.response.ResponsePayloadFactory instance at 0x7f7253984b00>, 'type': <Types.STRUCTURE: 1>, 'operation': Enumeration(enum=Operation, value=Operation.QUERY, tag=Tags.OPERATION)}`

Please fix the issue with the newer version of the pykmip release.

**Comment by PeterHamilton** [comment]
Hi @keyurgolanins, thanks for filing this issue. Going solely off of the error message in the above text, it looks like the Safenet server does not like the protocol version sent with the client request. However, I'm going to need more information to debug this problem.

Where did you get the above text (e.g., printing a Python structure, client log, etc)? Just so I'm on the right page, you are using the PyKMIP client (version 0.8.0) with a Safenet KMIP server, correct? Are you using one of the demo scripts? If so, which one(s)?

If the Safenet server doesn't like the protocol version, what versions does the server support? Do you know what version the client is sending? I can check to see if the client's default protocol version changed from PyKMIP 0.6 to 0.8.

**Comment by PeterHamilton** [comment]
Thanks for the additional details. However, I'm referring to the KMIP protocol version **not** the SSL/TLS protocol version. The KMIP spec has multiple versions (1.0 - 1.4). This version number is included in every request the client sends to the server. If your server doesn't support the KMIP version number, it may produce that error you're seeing.

I bumped the PyKMIP client's KMIP protocol version number to 1.2 right around the time I released PyKMIP 0.8. This could be causing the problem you're seeing. Unfortunately there's no way right now for you to easily revert that version number without modifying the client source code. Fortunately, I'm working on some other features right now that align with this so it'll be easy for me to add in a way for you to change the KMIP version number in the client. I'll continue working on this and will post an update to this issue once the client's ready.

**Comment by keyurgolanins** [comment]
Thanks for the update Peter. So I suppose that my KMIP server not
supporting default 1.2 protocol version is the issue for now. The options I
have is either wait for the feature to specify the kmip protocol version to
roll out in next release or have the kmip server support 1.2 version. Am I
taking this correct?

**Comment by PeterHamilton** [comment]
Yes, those are your only options right now. I may have a fix up later today but a new version of PyKMIP probably won't be released until January.

**Comment by PeterHamilton** [comment]
Once #472 merges you should be able to pull master and use `client.kmip_version` to access and modify the KMIP version used by the client. Note that if you're using the PyKMIP demo scripts you'll still need to modify those directly to change the KMIP version to the version you want.

**Comment by keyurgolanins** [comment]
Gotcha. Thanks Peter!
