### ISSUE TITLE
Get wrapped key raises ReadValueError due to unexpected Base.type

### ISSUE THREAD

**Issue by timpfel** [OpenKMIP/PyKMIP#484]
**Hi,**

I am using PyKMIP 0.8 and I have the following problem:
When I try to get a key wrapped I always receive the above error.

_File "...\kimp\core\primitives.py", line 84, in read_type
  typ
kmip.core.exceptions.ReadValueError: Tried to read Base.Type: expected 1, received 8_

It seems the read_type method expects Structure type but gets bytes instead.
The code I use is copied and pasted from the second example of:
https://pykmip.readthedocs.io/en/latest/client.html#kmip.pie.client.ProxyKmipClient.get
All the modification I made is I added names to the keys.

**Looking forward to your answer!
Regards,
Gabor**

**Comment by PeterHamilton** [comment]
Hi @timpfel, thanks for filing this issue. I'll need some additional information to help debug this. First, are you using the client with the PyKMIP server or are you using a third-party server? Second, can you provide the entire stack trace that the client produces? That will help me identify where in the decoding process the error occurs and specifically which part of the response message is causing the problem. Thanks!

**Comment by PeterHamilton** [comment]
Hi @timpfel, have you made any progress on this issue? It's been several days since you filed it. I'm happy to help as needed. If there is no additional work that needs to be done, I'll go ahead and close the issue.
