### ISSUE TITLE
Instructions for use with vCenter Server

### ISSUE THREAD

**Issue by whalehub** [OpenKMIP/PyKMIP#486]
It would be cool if you could add a guide to the Wiki on how to use PyKMIP with vCenter Server. Adding the server to it is simple enough, but I'm not sure how to then establish trust between the two afterwards.

**Comment by PeterHamilton** [comment]
Hi @whalehub, thanks for filing this issue. I do not know what version of vCenter you are using, however establishing trust should just come down to ensuring vCenter recognizes the certificate used to secure the PyKMIP server connections. There should be configuration options in vCenter that allow you to provide the PyKMIP CA or server certificate. Please see the PyKMIP server [configuration](https://pykmip.readthedocs.io/en/latest/server.html#configuration) and [authentication](https://pykmip.readthedocs.io/en/latest/server.html#authentication) documentation for more information.

Thanks also for the suggestion on adding a vCenter guide to the wiki. I'll consider adding it in the future.

**Comment by whalehub** [comment]
@PeterHamilton Is there any guide available on how to generate a certificate with the required extended key usage extension? I'm using [mkcert](https://github.com/FiloSottile/mkcert) to generate my certificates and it doesn't seem to support that right now.

**Comment by a2940uw** [comment]
Hi, I have same question of @whalehub , vmware vcenter start to support vm
guest vmdk encryption since 6.5 but require a KMS server to support, vmware
use PyKMIP for demonstration to encrypt guest vmdk initially, and all
official support kms server is no trial version in the market, therefore we
think PyKMIP can be archives.

Regards


在 2019年2月9日週六 上午4:02，Peter Hamilton <notifications@github.com> 寫道：

**Comment by PeterHamilton** [comment]
@whalehub For most of my testing I use [pyca/cryptography](https://github.com/pyca/cryptography) to programatically create certificates with the right properties (see [bin/create_certificates.py](https://github.com/OpenKMIP/PyKMIP/blob/master/bin/create_certificates.py) for an example). Using raw OpenSSL will likely require you to create a configuration file to specify what extensions you want. I've always found that tiresome to use so I created my own simple utility.

@a2940uw Thanks for chiming in!

**Comment by whalehub** [comment]
@PeterHamilton Thanks for the tip!
