### ISSUE TITLE
KMIP NetApp Client custom attributes

### ISSUE THREAD

**Issue by jahluwalia** [OpenKMIP/PyKMIP#489]
Hi,

I'm trying to use PyKMIP for testing purposes using a netapp client. They have some custom attributes and I'm getting the ResultMessage `The x-NETAPP-ClusterName attribute is unsupported.` There are about 16 custom attributes that netapp is using. When we intercept in process_template_attribute in engine.py, i see that the types of each attribute are strings via `print(type(attribute.atribute_value.value))` (perhaps they got converted before hand?). 

We also added each attribute to the dictionary in policy.py following the example of `'Custom Attribute'`

Is there some pointers you could give us to get these specific 16 custom attributes working? 

Thanks,
Jas

**Comment by jahluwalia** [comment]
Just to follow with an FYI,

We used `https://github.com/callidus/DecodeTTLV ` to see that the values of the all the custom attributes (x-*) are in fact STRING.

Thanks,
Jas

**Comment by PeterHamilton** [comment]
Hi @jahluwalia, thanks for filing this issue. It looks like you've already done some digging on this and are close to a working solution. There are three places in [kmip/services/server/engine.py](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/engine.py) that can generate the `X attribute is unsupported` error that you're seeing, [here](https://github.com/OpenKMIP/PyKMIP/blob/dcade2a2640fc4bcb9ca0b817c2e2fa30cd9e4b2/kmip/services/server/engine.py#L548), [here](https://github.com/OpenKMIP/PyKMIP/blob/dcade2a2640fc4bcb9ca0b817c2e2fa30cd9e4b2/kmip/services/server/engine.py#L766), and [here](https://github.com/OpenKMIP/PyKMIP/blob/dcade2a2640fc4bcb9ca0b817c2e2fa30cd9e4b2/kmip/services/server/engine.py#L799). If you edited [kmip/services/server/policy.py](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/policy.py#L1047) correctly (following `Custom Attribute` as you indicated) you should have fixed the first one. To fix the second one, comment out lines 763-767 ([here](https://github.com/OpenKMIP/PyKMIP/blob/dcade2a2640fc4bcb9ca0b817c2e2fa30cd9e4b2/kmip/services/server/engine.py#L766)). To fix the third one, comment out lines 796-800 ([here](https://github.com/OpenKMIP/PyKMIP/blob/dcade2a2640fc4bcb9ca0b817c2e2fa30cd9e4b2/kmip/services/server/engine.py#L799)). Note that this is only a bandaid fix; the PyKMIP server isn't able to store those custom attributes. Commenting out the above sections just prevents the server from failing while processing them; with the comments it just acts like those attributes don't exist. If your NetApp client relies on them for any other operations, those operations will likely fail.

**Comment by jahluwalia** [comment]
HI @PeterHamilton,

Thank you for the response.  So before you had responded, I made a different set of changes to the method `set_attribute_on_managed_object` instead of commenting out the exceptions like you suggested. Here is what I did in that method (around the 790 range). It seems to be working well (including registers, locates, revokes, destroys), but let me know if you can think of any negative consequences. 

```
elif attribute_name.startswith( 'x-' ):
    self._logger.info("Jas: Setting field to Custom Attribute name {0}".format(attribute_name))
    field = attribute_name

if field:
    existing_value = None #getattr(managed_object, field)
```

I do have anotehr question for you. How do you debug pykmip? I'm finding the multiprocessing is limiting us in vscode. What tools do you use? Being able to break and step would be really helpful. If i should start another issue about debugging, let me know and I can do that. Or you can answer here. 

Thanks for your help,
Jas

**Comment by PeterHamilton** [comment]
No problem, I'm glad you found a fix that seems to be working for you.

As for the debugging question, let's move that to another issue. I'll go ahead and close this one for now.
