### ISSUE TITLE
Debugger Reccomendations

### ISSUE THREAD

**Issue by jahluwalia** [OpenKMIP/PyKMIP#490]
Hi,

What tools and procedures have you used to debug. We've tried to use vscode to remote attach to pykmip, and we've tried pdb locally. Any help would greatly be appreciated. 

Thanks,
Jas

**Comment by PeterHamilton** [comment]
In the past I've used pdb to handle tricky bugs, but it's been a while. I have not attempted to use Visual Studio for Python debugging, though I have used it's debugger for other languages and it is fantastic. 

For the PyKMIP client it is possible to enable debug logging, which will dump all of the TTLV-encoded messages sent and received by the client to the client log. Unfortunately we never added that capability to the server.

You mentioned in #489 that you were having issues with Visual Studio debugging with Python multiprocessing; can you provide more information on that?

**Comment by jahluwalia** [comment]
Hi @PeterHamilton 

We just started using pdb and that seems to be working well for us. I do have questions about printing TTLV

I'm currently printing the request TTLV bytes in session.py based on something you wrote in another issue as follows in `handle_message_loop`

`self._logger.info("KSNG: request.buffer: {0}".format(binascii.hexlify(request_data.buffer)))`

I then added decode.py from the DecodeTTLV project to the pykmip prjoect and decode it there. It required some tweaks to print to a variable instead of stdout. 

So my questions:
1) Does the client print the decoded ttlv or just the hex bytes? if it's decoded, i might use your code instead of mine. can you point me to it?
2) Where is a good place to print the response ttlv and decode that in the server?

thanks,
jas

**Comment by PeterHamilton** [comment]
The client just logs the hex bytes so using DecodeTTLV makes sense. That project was created years ago to actually help do dev work on PyKMIP, so I'm glad it's helping out here. You can find the relevant client lines [here (write)](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/kmip_protocol.py#L38) and [here (read)](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/kmip_protocol.py#L54).

For the server, see [here (write)](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/session.py#L344) and [here (read)](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/services/server/session.py#L315).

**Comment by jahluwalia** [comment]
Awesome. Thanks for that. When we're printing the responses, I notice that some TTLVs fail to decode. I think the type is off, it treats the attribute_value as enumerations instead of strings. Any idea why that would happen to responses? 

thanks,
jas

**Comment by PeterHamilton** [comment]
That's interesting. Do you know which attributes are causing the failures? The KMIP specification does sometimes update the type of minor values; it's possible I updated PyKMIP in the past to reflect that and knocked it out of sync with DecodeTTLV.

**Comment by PeterHamilton** [comment]
Hi @jahluwalia, is there anything further I can help you with on this issue? If not, I'll go ahead and close it.

**Comment by PeterHamilton** [comment]
Hi @jahluwalia, I'm going to go ahead and close this issue. Feel free to comment here or file a new issue if anything comes up. Thanks!
