### ISSUE TITLE
Test for Maximum Items in Locate

### ISSUE THREAD

**Issue by Grehgous** [OpenKMIP/PyKMIP#524]
I have not been able to find any integration tests for Locate which specify Maximum Items in the request.

I am looking to send a Locate request to a third-party KMIP server using KMIP 1.3, and validate that it respects my specified Maximum Items.

**Comment by PeterHamilton** [comment]
Hi @Grehgous, thanks for filing this. That doesn't surprise me; while extensive, our overall test suite doesn't cover every facet of the KMIP spec. I'll take a look at how Locate is currently tested in the integration tests and will add coverage for MaximumItems.

**Comment by Grehgous** [comment]
I'm writing tests, but i'm new to Python. How can I print `message`, type `RequestMessage` in TTLV format?

```
    def _locate(self, maximum_items=None, storage_status_mask=None,
                object_group_member=None, attributes=None, credential=None):

        operation = Operation(OperationEnum.LOCATE)

        payload = payloads.LocateRequestPayload(
            maximum_items=maximum_items,
            storage_status_mask=storage_status_mask,
            object_group_member=object_group_member,
            attributes=attributes
        )

        batch_item = messages.RequestBatchItem(
            operation=operation,
            request_payload=payload
        )

        message = self._build_request_message(credential, [batch_item])

        # How do I print this as ttlv?
        print("\nLocate request:\n", message) 
        
        self._send_message(message)
        message = messages.ResponseMessage()
        data = self._receive_message()

        print("\nLocate response:\n", data)
```

**Comment by PeterHamilton** [comment]
To encode a structure in TTLV format, use the object's `write` method, like this:

```
from kmip.core import utils

buffer = utils.BytearrayStream()
message.write(buffer)
print(str(buffer))
```

**Comment by Grehgous** [comment]
That's exactly what I was looking for, thanks!

Side note: I developed a KMIP client in a different language, and i'm considering becoming a contributor to PyKMIP. Is there a channel set up for for the project's developers to chat?

**Comment by PeterHamilton** [comment]
I used to maintain a PyKMIP room (#pykmip) on Freenode IRC. It's never active since I'm the only active dev on the project but I'm happy to hang out there if you want to chat.

**Comment by PeterHamilton** [comment]
Hi @Grehgous, I finally added in several integration tests that verify that `maximum_items` is enforced properly in the PyKMIP server for the `Locate` operation. See [test_proxykmipclient.py#L1230](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/tests/integration/services/test_proxykmipclient.py#L1230) and [test_integration.py#L1597](https://github.com/OpenKMIP/PyKMIP/blob/master/kmip/tests/integration/services/test_integration.py#L1597).

Not sure if this directly applies to what you were originally looking for but I figured I'd let you know. For now I'm going to close this issue. Feel free to comment or pick up the discussion again if there's anything else you need.
