### ISSUE TITLE
Minimum required version of cryptography

### ISSUE THREAD

**Issue by jack-fortanix** [OpenKMIP/PyKMIP#525]
Currently requirements has ``cryptography>=1.3`` but ``kmip/services/server/crypto/engine.py`` imports `from cryptography.hazmat.primitives.kdf import kbkdf`, kbkdf was added in cryptography 1.4

**Comment by PeterHamilton** [comment]
Hi @jack-fortanix, thanks for pointing this out. I'll take a look and bump requirements if needed.

**Comment by PeterHamilton** [comment]
Finally got around to checking this and you're right, `cryptography` should be pinned to `>=1.4`. I'll fix that right now. Thanks!
