### ISSUE TITLE
Add client/server storage/generation support for split keys

### ISSUE THREAD

**Issue by PeterHamilton** [OpenKMIP/PyKMIP#545]
Add client and server capabilities to store and generate split key objects. Currently, split keys are only supported as opaque objects.

**Comment by KBassford** [comment]
Hi Peter, 
I've been following along while I've been working on other parts of my project and looking at the latest code brings to mind a question.  I don't see any provision for user generated/unique primes in the storage of split keys.  Will that be supported?

**Comment by PeterHamilton** [comment]
> provision for user generated/unique primes in the storage of split keys

I don't think I fully know what you mean by this. Can you provide more information?

**Comment by KBassford** [comment]
Nevermind, looking back at the specs I see the "Prime Field Size" (why "size" is in the name, God only knows) is where the prime field is saved.  At least in my implementation, which it looks like you're following and improving upon.  Sorry for the false alarm.

**Comment by PeterHamilton** [comment]
Ah, ok, that makes sense. No problem.
