### ISSUE TITLE
Locate function behavior change

### ISSUE THREAD

**Issue by KBassford** [OpenKMIP/PyKMIP#556]
Hi Peter,

Prior to implementation of KMIP 2.0, an empty _locate_ function could be used to get a list of all the object uid's stored on the server.  If one however sets their query to `kmip_version=enums.KMIPVersion.KMIP_2_0`, the following error results when attempting the same operation ...

```
locate(
    maximum_items=None,
    storage_status_mask=None,
    object_group_member=None,
    attributes=[]
)

Traceback (most recent call last):
  File "src/local-gitlab.com/gkbassf/go-pykmip-wrapper/kmiplocate/kmip_locate.py", line 128, in <module>
    main(args)
  File "src/local-gitlab.com/gkbassf/go-pykmip-wrapper/kmiplocate/kmip_locate.py", line 110, in main
    attributes=[]
  File "/usr/local/lib/python3.7/dist-packages/kmip/pie/client.py", line 39, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kmip/pie/client.py", line 709, in locate
    object_group_member, attributes)
  File "/usr/local/lib/python3.7/dist-packages/kmip/services/kmip_client.py", line 701, in locate
    attributes=attributes, credential=credential)
  File "/usr/local/lib/python3.7/dist-packages/kmip/services/kmip_client.py", line 1496, in _locate
    self._send_message(message)
  File "/usr/local/lib/python3.7/dist-packages/kmip/services/kmip_client.py", line 1604, in _send_message
    message.write(stream, self.kmip_version)
  File "/usr/local/lib/python3.7/dist-packages/kmip/core/messages/messages.py", line 494, in write
    batch_item.write(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.7/dist-packages/kmip/core/messages/messages.py", line 331, in write
    self.request_payload.write(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.7/dist-packages/kmip/core/messages/payloads/locate.py", line 321, in write
    "The Locate request payload is missing the attributes "
kmip.core.exceptions.InvalidField: The Locate request payload is missing the attributes list.
```
Same result if one sets `attributes=None`.  Setting the version back to KMIP_1_4 restores prior (proper) behavior.

**According to KMIP 2.0, Table 229: Locate Request Payload**
***Item=***  Attributes
***Required=***  Yes
***Description=***  Specifies an attribute and its value(s) that are REQUIRED to match those in a candidate object (according to the matching rules defined above). Note: the Attributes structure MAY be empty indicating all objects should match.

Additional side note: Function should also allow the specification of an offset_items (optional)  An Integer object that indicates the number of object identifiers to skip that satisfy the identification criteria specified in the request.

**Comment by PeterHamilton** [comment]
Thanks for reporting this issue. I missed this in testing, sorry about that. You're right, the latest version of the KMIP 2.0 spec allows for the attributes field to be empty, preserving backwards compatibility. However, the initial version of the KMIP 2.0 spec doesn't; see:

https://docs.oasis-open.org/kmip/kmip-spec/v2.0/csd01/kmip-spec-v2.0-csd01.html#_Toc534979942

I updated `Locate` off of that initial version of the spec. The latest version came out a couple of months ago and I missed the loosening of the constraints on the attributes field.

I'll put together a patch for `Locate` and cut a quick 0.9.1 release fixing it.

**Comment by KBassford** [comment]
No problem, one of the hazards of trying to hit a moving target.

**Comment by KBassford** [comment]
Sorry to say, just rebuilt my server and this issue is unaffected.

Using 1.4 ...
└──╼ $src/local-gitlab.com/gkbassf/go-pykmip-wrapper/tools/pykmip/pykmip_dispatch.py locate 
{'uids': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']}

Using 2.0
┌─[kbassford@Portunus]─[~/go]
└──╼ $src/local-gitlab.com/gkbassf/go-pykmip-wrapper/tools/pykmip/pykmip_dispatch.py locate 
Traceback (most recent call last):
  File "src/local-gitlab.com/gkbassf/go-pykmip-wrapper/tools/pykmip/pykmip_dispatch.py", line 1557, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "src/local-gitlab.com/gkbassf/go-pykmip-wrapper/tools/pykmip/pykmip_dispatch.py", line 486, in locate
    object_group_member=group_enum,
  File "/usr/local/lib/python3.7/dist-packages/kmip/pie/client.py", line 39, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kmip/pie/client.py", line 709, in locate
    object_group_member, attributes)
  File "/usr/local/lib/python3.7/dist-packages/kmip/services/kmip_client.py", line 701, in locate
    attributes=attributes, credential=credential)
  File "/usr/local/lib/python3.7/dist-packages/kmip/services/kmip_client.py", line 1496, in _locate
    self._send_message(message)
  File "/usr/local/lib/python3.7/dist-packages/kmip/services/kmip_client.py", line 1604, in _send_message
    message.write(stream, self.kmip_version)
  File "/usr/local/lib/python3.7/dist-packages/kmip/core/messages/messages.py", line 494, in write
    batch_item.write(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.7/dist-packages/kmip/core/messages/messages.py", line 331, in write
    self.request_payload.write(tstream, kmip_version=kmip_version)
  File "/usr/local/lib/python3.7/dist-packages/kmip/core/messages/payloads/locate.py", line 321, in write
    "The Locate request payload is missing the attributes "
kmip.core.exceptions.InvalidField: The Locate request payload is missing the attributes list.

**Comment by PeterHamilton** [comment]
Hmmm, interesting. I'll reopen this issue and dig into this later this afternoon. Thanks for the update and apologies again for the bug.

**Comment by PeterHamilton** [comment]
I've retested the `Locate` operation with no attribute arguments, for both KMIP 2.0 and older spec versions (1.3, 1.4) and it returns the full list of object IDs stored by the server every time.

Can you confirm that you're running PyKMIP 0.9.1? The exception message you're seeing, `The Locate request payload is missing the attributes list.` is not included anywhere in the 0.9.1 code base nor is it in the master branch.

**Comment by KBassford** [comment]
┌─[kbassford@Portunus]─[~/go]
└──╼ $sudo pip3 freeze | grep PyKMIP
PyKMIP==0.9.1
┌─[kbassford@Portunus]─[~/go]
└──╼ $src/local-gitlab.com/gkbassf/go-pykmip-wrapper/tools/pykmip/pykmip_dispatch.py locate --attrs="{'Name': '61735_RSA_Private_Key'}" --debug
locate(
    attributes=[Attribute(attribute_name=AttributeName(value='Name'), attribute_index=AttributeIndex(value=0), attribute_value=Name(type=NameType(value=<NameType.UNINTERPRETED_TEXT_STRING: 1>),value=NameValue(value='61735_RSA_Private_Key')))]
)

{
    "uids": []
}

{'uids': []}
┌─[kbassford@Portunus]─[~/go]
└──╼ $src/local-gitlab.com/gkbassf/go-pykmip-wrapper/tools/pykmip/pykmip_dispatch.py get-attributes --uid=333 --debug
get_attributes(
    uid=333,
    attribute_names=[],
)

Object Attribute List ...
("['Cryptographic Algorithm', 'Cryptographic Length', 'Cryptographic Usage "
 "Mask', 'Initial Date', 'Object Type', 'State', 'Unique Identifier']")

Object Attributes ...
("('333', [Attribute(attribute_name=AttributeName(value='Object Type'), "
 'attribute_index=None, attribute_value=Enumeration(enum=ObjectType, '
 'value=ObjectType.PRIVATE_KEY, tag=Tags.ATTRIBUTE_VALUE)), '
 "Attribute(attribute_name=AttributeName(value='Cryptographic Usage Mask'), "
 'attribute_index=None, attribute_value=CryptographicUsageMask(value=1)), '
 "Attribute(attribute_name=AttributeName(value='Cryptographic Length'), "
 'attribute_index=None, attribute_value=CryptographicLength(value=2048)), '
 "Attribute(attribute_name=AttributeName(value='Cryptographic Algorithm'), "
 'attribute_index=None, '
 'attribute_value=Enumeration(enum=CryptographicAlgorithm, '
 'value=CryptographicAlgorithm.RSA, tag=Tags.ATTRIBUTE_VALUE)), '
 "Attribute(attribute_name=AttributeName(value='Initial Date'), "
 'attribute_index=None, attribute_value=DateTime(value=1563554381, '
 'tag=Tags.ATTRIBUTE_VALUE)), '
 "Attribute(attribute_name=AttributeName(value='Unique Identifier'), "
 "attribute_index=None, attribute_value=UniqueIdentifier(value='333')), "
 "Attribute(attribute_name=AttributeName(value='State'), attribute_index=None, "
 'attribute_value=Enumeration(enum=State, value=State.PRE_ACTIVE, '
 'tag=Tags.ATTRIBUTE_VALUE))])')

attributes: ('333', [Attribute(attribute_name=AttributeName(value='Object Type'), attribute_index=None, attribute_value=Enumeration(enum=ObjectType, value=ObjectType.PRIVATE_KEY, tag=Tags.ATTRIBUTE_VALUE)), Attribute(attribute_name=AttributeName(value='Cryptographic Usage Mask'), attribute_index=None, attribute_value=CryptographicUsageMask(value=1)), Attribute(attribute_name=AttributeName(value='Cryptographic Length'), attribute_index=None, attribute_value=CryptographicLength(value=2048)), Attribute(attribute_name=AttributeName(value='Cryptographic Algorithm'), attribute_index=None, attribute_value=Enumeration(enum=CryptographicAlgorithm, value=CryptographicAlgorithm.RSA, tag=Tags.ATTRIBUTE_VALUE)), Attribute(attribute_name=AttributeName(value='Initial Date'), attribute_index=None, attribute_value=DateTime(value=1563554381, tag=Tags.ATTRIBUTE_VALUE)), Attribute(attribute_name=AttributeName(value='Unique Identifier'), attribute_index=None, attribute_value=UniqueIdentifier(value='333')), Attribute(attribute_name=AttributeName(value='State'), attribute_index=None, attribute_value=Enumeration(enum=State, value=State.PRE_ACTIVE, tag=Tags.ATTRIBUTE_VALUE))])

UID: 333
attrparams: {'attribute_name': 'Object Type', 'attribute_index': 'None', 'attribute_value': 'ObjectType.PRIVATE_KEY'}
attribute_name: 'Object Type'
attribute_index: None
attribute_value: 'PRIVATE_KEY'

attrparams: {'attribute_name': 'Cryptographic Usage Mask', 'attribute_index': 'None', 'attribute_value': '1'}
attribute_name: 'Cryptographic Usage Mask'
attribute_index: None
attribute_value: 1
Mask: ['SIGN']

attrparams: {'attribute_name': 'Cryptographic Length', 'attribute_index': 'None', 'attribute_value': '2048'}
attribute_name: 'Cryptographic Length'
attribute_index: None
attribute_value: 2048

attrparams: {'attribute_name': 'Cryptographic Algorithm', 'attribute_index': 'None', 'attribute_value': 'CryptographicAlgorithm.RSA'}
attribute_name: 'Cryptographic Algorithm'
attribute_index: None
attribute_value: 'RSA'

attrparams: {'attribute_name': 'Initial Date', 'attribute_index': 'None', 'attribute_value': 'Fri Jul 19 16:39:41 2019'}
attribute_name: 'Initial Date'
attribute_index: None
attribute_value: 1563554381
Date: Fri Jul 19 16:39:41 2019

attrparams: {'attribute_name': 'Unique Identifier', 'attribute_index': 'None', 'attribute_value': '333'}
attribute_name: 'Unique Identifier'
attribute_index: None
attribute_value: '333'

attrparams: {'attribute_name': 'State', 'attribute_index': 'None', 'attribute_value': 'State.PRE_ACTIVE'}
attribute_name: 'State'
attribute_index: None
attribute_value: 'PRE_ACTIVE'

('333', {'Object Type': 'PRIVATE_KEY', 'Cryptographic Usage Mask': ['SIGN'], 'Cryptographic Length': 2048, 'Cryptographic Algorithm': 'RSA', 'Initial Date': 'Fri Jul 19 16:39:41 2019', 'Unique Identifier': '333', 'State': 'PRE_ACTIVE'})

**Comment by KBassford** [comment]
Nevermind, just got it working.  Will send current test scripts.

**Comment by PeterHamilton** [comment]
Given the bulk of the `Locate` work is complete for now, I'm going to go ahead and close this issue. Feel free to comment here again if further discussion is warranted.
