### ISSUE TITLE
Locate function does not handle offset.

### ISSUE THREAD

**Issue by KBassford** [OpenKMIP/PyKMIP#562]
As far as I'm concerned, offset is fairly useless.  Just noting that there is no provision in the client for `offset`.

Side Note: `group` appears to be implemented, but does not seem to do anything.

Are there any attributes besides `Name` useable in this function?

**Comment by PeterHamilton** [comment]
> As far as I'm concerned, offset is fairly useless. Just noting that there is no provision in the client for `offset`.

Correct, the clients don't support the `offset` field yet. The underlying `Locate` request/response messages do but I still need to punch the right holes in the client interfaces.

> Side Note: `group` appears to be implemented, but does not seem to do anything.

If you're referring to the `object_group_member` field, that is related to the `object_group` attribute but is not the `object_group` itself. The `object_group` attribute is not currently supported.

> Are there any attributes besides `Name` useable in this function?

No, right now only filtering on `Name` attributes is supported.

I'm going to be working on `Locate` support this week and will be adding in filter support for other currently supported attributes (e.g., `object_type`, `state`, etc). So, improvements coming soon!
