### ISSUE TITLE
Hashicorp Vault KMIP client: kmip.core.exceptions.ReadValueError: Tried to read Base.tag

### ISSUE THREAD

**Issue by MahmoudMansourr** [OpenKMIP/PyKMIP#710]
I have Hashicorp vault set up as a KMIP server and i'm trying to configure the PyKIMP client, on the vault side it gets the request and executes it and returns a response but from the client side i get this:

ERROR starts here:

Traceback (most recent call last):
  File "/root/main.py", line 36, in <module>
    client.destroy('jI9VyxJd1REqGFae7mSSSgD3lEjI3aax')
  File "/usr/lib/python3/dist-packages/kmip/pie/client.py", line 41, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/kmip/pie/client.py", line 1177, in destroy
    result = self.proxy.destroy(uid)
  File "/usr/lib/python3/dist-packages/kmip/services/kmip_client.py", line 787, in destroy
    return self._destroy(unique_identifier=uuid,
  File "/usr/lib/python3/dist-packages/kmip/services/kmip_client.py", line 1503, in _destroy
    message.read(data, self.kmip_version)
  File "/usr/lib/python3/dist-packages/kmip/core/messages/messages.py", line 520, in read
    self.response_header.read(istream, kmip_version=kmip_version)
  File "/usr/lib/python3/dist-packages/kmip/core/messages/messages.py", line 208, in read
    self.batch_count.read(tstream, kmip_version=kmip_version)
  File "/usr/lib/python3/dist-packages/kmip/core/primitives.py", line 228, in read
    super(Integer, self).read(istream, kmip_version=kmip_version)
  File "/usr/lib/python3/dist-packages/kmip/core/primitives.py", line 105, in read
    self.read_tag(istream)
  File "/usr/lib/python3/dist-packages/kmip/core/primitives.py", line 56, in read_tag
    raise exceptions.ReadValueError(
kmip.core.exceptions.ReadValueError: Tried to read Base.tag: expected 0x42000d, received 0x420106

has anyone faced a problem like this before?

EDIT:
the problem was solved by installing the version present on the repo itself, not using pip to install pykmip.

**Comment by tearfulDalvik** [comment]
I have this problem too

**Comment by MahmoudMansourr** [comment]
> I have this problem too

I found it that the problem was caused by the version of the pykmip as I was using pip to install the library, use the github repo instead.
if you follow the installation guide here: https://github.com/karimjawhar5/Key-Managment-System it should work.
Out of curiosity, are you also using hashicorp vault as a server?

**Comment by tearfulDalvik** [comment]
> > I have this problem too
> 
> I found it that the problem was caused by the version of the pykmip as I was using pip to install the library, use the github repo instead. if you follow the installation guide here: [karimjawhar5/Key-Managment-System](https://github.com/karimjawhar5/Key-Managment-System) it should work. Out of curiosity, are you also using hashicorp vault as a server?

Thank you very much for your advise. Yes, I'm using hashicorp vault as kmip server.

**Comment by tearfulDalvik** [comment]
> > I have this problem too
> 
> I found it that the problem was caused by the version of the pykmip as I was using pip to install the library, use the github repo instead. if you follow the installation guide here: [karimjawhar5/Key-Managment-System](https://github.com/karimjawhar5/Key-Managment-System) it should work. Out of curiosity, are you also using hashicorp vault as a server?

Hello friend, I tried to follow the guide. A quick question, are you using master, or latest release tag 0.10.0?

**Comment by MahmoudMansourr** [comment]
Sorry for the late reply, what do you mean master? the version i'm using is 0.11.dev.
if you have discord, we can chat there.
my user is "horrific_dev"

**Comment by tearfulDalvik** [comment]
Thank you very much. 
After investigating, I found that the problem is fixed at https://github.com/OpenKMIP/PyKMIP/pull/695

**Comment by MahmoudMansourr** [comment]
Install the version present on this repo, don't use pip to install
